### ISSUE TITLE
Create the left-side navigation sidepanel

### ISSUE THREAD

**Issue by zyrrus** [zyrrus/resume-factory#3]
- Create a `layout.tsx` file in `src/app/(app)/` 
- Implement the sidepanel from Figma (I suggest just using absolute positioning with top, left, and bottom all set to 0 for now and we can figure out a more responsive solution later once we get the resume editor window figured out)

**Comment by begench-g** [comment]
Hello. I would like to work on this issue. Could you assign it issue to me?
